### PR TITLE
add files completion to Ag

### PR DESCRIPTION
**Pull request by ryanong**

### CODE REVIEW

**Comment by junegunn** [comment]
Can you elaborate? Ag command takes a search query as its argument not a name of a file.

**Comment by junegunn** [comment]
Is it because you find it useful to have file names easily accessible on command line even though it's not semantically correct?

**Comment by ryanong** [comment]
Ag accepts paths beyond the first argument to search. So if I want to search a specific directory or file I use that as the second argument

**Comment by junegunn** [comment]
No, `Ag` from this repository does not accept any path argument. The whole string, including white spaces, is passed to `ag` command as the query. So I'm concerned that enabling file completion might confuse the users. It has been suggested that one who wants to customize the behavior should define a custom command using the underlying autoload function. See #27, #92, #144 for the details.

**Comment by junegunn** [comment]
Please consider defining your own command using `fzf#vim#grep` function.

```vim
command! -bang -nargs=* -complete=dir Dag
  \ call fzf#vim#grep('ag --nogroup --column --color '.join(map([<f-args>], 'shellescape(v:val)')), 0, <bang>0)
```

**Pull request closed without merging**
