### PR TITLE
Smart case for rg (readme)

### PR DESCRIPTION
**Pull request by dylan-chong**
Is now consistent with Ag. And more convenient

### CODE REVIEW

**Comment by junegunn** [comment]
> Is now consistent with Ag

Thanks, but I think you're somehow confused. Ag is case-sensitive.

**Comment by dylan-chong** [comment]
Are you sure?

screen shot 2018-06-20 at 8 30 18 pm
screen shot 2018-06-20 at 8 30 20 pm

**Comment by dylan-chong** [comment]
Ah, ag is smartcase by default. We could change rg to be consistent with that

**Comment by junegunn** [comment]
Yeah, that makes sense. Thanks.

**Comment by dylan-chong** [comment]
Could you reopen this if you would like me to change it?

**Comment by dylan-chong** [comment]
Done @junegunn

**Comment by junegunn** [comment]
Thanks!

**Pull request merged**
