### PR TITLE
Unfold after Lines/BLines

### PR DESCRIPTION
**Pull request by dsh2**
Actually I would want the unfold to only happen, if the matched line is really hidden within a fold. In the current version of the PR, the fold will also be unfolded when the matched line is the beginning of the fold. Unfortunately, I did not find any way to tell, if the current line is hidden within a fold.

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, I think it would be better to do `zz` after `zv`, so `zvzz`. What do you think?

**Comment by dsh2** [comment]
Yes! That's more natural - I think. I actually tend to have scrolloff=999 so I did not notice. By the way: Maybe you have an idea how one could check for the above mentioned problem with the first line?

**Comment by dsh2** [comment]
I fear I don't get it. Maybe you mean `==` instead of `&&`? 

Even worse, I don't get what I meant in my first message of the PR. I think I mixed up the first line of a fold with the result of `foldtext()` -- which often times is very similar to the first line of a fold. 

Indeed `zv` just opens enough folds to make the line visible, i.e.not folded, in which the cursor is located at. So we could simply go for the `zvzz`-approach.

**Comment by junegunn** [comment]
Okay, let's keep it simple.

**Pull request merged**
