### PR TITLE
Add option to use location list instead of quickfix list

### LINKED ISSUE #432: ability to choose qf/location list
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- Vim
    - [ ] Vim
    - [x] Neovim

I've started to write some functions to be able to choose a quickfix/location list among the ones loaded (visibler through :chistory) but it's not easy dealing with :chistory/:colder/:cnewer . Is there any existing implementation someone would know of ? If no, is that sthg that could make it to fzf.vim ?

### LINKED ISSUE #448: option for using location instead of quickfix for :Ag
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

Hi, is it possible to add a option to use location instead of quickfix for the example shown in this issue: #185 ?

I'm currently using the following function to generate a location list:
```vimscript
function! s:build_location_list(lines)
  call setloclist(0, map(copy(a:lines), '{ "filename": v:val }'))
  lopen
  ll
endfunction
```
This does not work with `:Ag` hoewer, where i had to modifiy `autoload/fzf/vim.vim::631`

### PR DESCRIPTION
**Pull request by nkouevda**
Fixes #432, fixes #448.

Feel free to close this if you don't want it; I see the readme says this repo is "_not_ designed to be flexible or configurable", so totally understandable.

### CODE REVIEW

**Comment by junegunn** [comment]
You might want to check out #846.

Can you explain why you want to (have to) use the location list instead of the quickfix list?

**Comment by nkouevda** [comment]
Partially habit / convenience / consistency; I'm used to using location lists instead of the quickfix list, and navigating items with vim-unimpaired's `[l` / `]l` instead of `[q` / `]q`. e.g. I use [your `s:build_quickfix_list` example](https://github.com/junegunn/fzf/blob/0f50dc848e58b47408713c2c31f2be73287c030a/README-VIM.md#examples), but [using location list](https://github.com/nkouevda/dotfiles/blob/73e38daaf6a647f7419583fd9c304cdac7cdaaf5/.vim/vimrc#L287) instead. (But [as you explained](https://github.com/junegunn/fzf.vim/issues/1345#issuecomment-963743146) that doesn't work for `:Rg`, which is how I ended up here.)

And in terms of functionality, this allows having multiple lists, e.g. I have wanted to search for different things in different windows, and to iterate through the results separately.

But admittedly (1) is entirely subjective, and (2) is not a particularly common use case in my experience.

**Comment by junegunn** [comment]
Thanks for the clarification.

> this allows having multiple lists

If that's the case, we should probably provide a way to use a different list type per command. I'll see what I can do.

**Comment by junegunn** [comment]
See 832a090870a79d8be87d8856c821806512a45b23.

It's a pretty big change, so please give it a try and let me know how it works.

```vim
let g:fzf_vim = {}
let g:fzf_vim.listproc = { list -> fzf#vim#listproc#location(list) }
```

**Comment by nkouevda** [comment]
Works great; thank you!

I don't use `preview_bash`, but noticed that needs a little fix: #1502

**Pull request closed without merging**
