### PR TITLE
[fzf#vim#colors] Remove duplicate colorschemes

### PR DESCRIPTION
**Pull request by mklein994**
This makes it work more intuitively with plugins like [flazz/vim-colorschemes](https://github.com/flazz/vim-colorschemes).

### CODE REVIEW

**Comment by junegunn** [comment]
Please update the code to use `s:uniq()`. `uniq()` is not available on older versions of Vim.

**Comment by mklein994** [comment]
This would be my first venture into VimL, as I'm fairly new to writing plugins for Vim, but I could give it a shot. Do you have any style guidelines you want me to follow?

**Comment by junegunn** [comment]
There's already `s:uniq` function defined in that file. All you have to do is to replace `uniq (...)` with `s:uniq (...)`.

**Comment by mklein994** [comment]
Can't believe I didn't see that… ah well.

**Comment by junegunn** [comment]
Thanks for the update. Oh, by the way, can you remove `sort()`? `s:uniq` does not require the list to be sorted. Currently, non-system color schemes installed with vim-plug are listed before the ones that come with Vim by default, and I like the ordering.

**Comment by junegunn** [comment]
Merged, thanks!

**Pull request merged**
