### PR TITLE
Add :Wipeouts command for deleting buffers

### PR DESCRIPTION
**Pull request by kyoh86**
for: #380 , #75

### CODE REVIEW

**Comment by haringsrob** [comment]
I have fuctionally tested this and works great. Verry usefull feature. But perhaps allow the keybind to be configurable?

**Comment by kyoh86** [comment]
@haringsrob I did it.
@junegunn How's this?

**Comment by evmorov** [comment]
Are you sure that the note "Press $key to wipeout a buffer" is needed? Personally, for me, it looks distracting. Usually, vim plugins don't show help and especially shortcuts when you use them.

Can we leave fzf window open after deleting a buffer? Sometimes It's needed to delete multiple buffers.

**Comment by kyoh86** [comment]
@evmorov 
Thank you for your review.

> Are you sure that the note "Press $key to wipeout a buffer" is needed? Personally, for me, it looks distracting

`:Commits` and `:History [:/]` shows help line too.
So I thought that `fzf` should show extra key bindings.
But, what you're saying is reasonable.

It should be solved with some options, shouldn't it?

```
let g:fzf_commits_show_keybindings = 0
let g:fzf_history_show_keybindings = 0
let g:fzf_buffers_show_keybindings = 0
```

> Sometimes It's needed to delete multiple buffers.

I agree with you. I want to fix it.

**Comment by kyoh86** [comment]
> > Sometimes It's needed to delete multiple buffers.

> I agree with you. I want to fix it.

It cannot be solved with current implementing...
I found that this function should be implemented as new command like `:Wipeouts`.

**Comment by ranebrown** [comment]
@junegunn Any chance of this getting merged?

**Comment by kyoh86** [comment]
@junegunn I resolved conflicts.
please merge this one.

**Comment by junegunn** [comment]
Thanks for the pull request, but I'm not interested in accepting and maintaining features that I don't actually need. I just don't have the bandwidth.

**I really want to stress that you can easily implement fzf-based commands in your configuration files. They don't have to reside in this single repository.** Please read through https://github.com/junegunn/fzf/blob/master/README-VIM.md and learn how to write custom commands.

Believe me, it's pretty simple if you know the drill. Put this code in your Vim configuration file, and you have `:BD` command for the suggested behavior. And you can customize it however you want, whenever you want, without having to wait for me to add some `g:fzf_buffer_delete_xxx` and stuff.

```vim
function! Bufs()
  redir => list
  silent ls
  redir END
  return split(list, "\n")
endfunction

command! BD call fzf#run(fzf#wrap({
  \ 'source': Bufs(),
  \ 'sink*': { lines -> execute('silent bwipeout '.join(map(lines, {_, line -> split(line)[0]}))) },
  \ 'options': '-m --reverse'
\ }))
```

**Comment by kyoh86** [comment]
ok, I gave up my idea.
fzf.vim has a attractive function (s:buflist_sorted), I wanted use them but they are not published...

**Comment by amadeus** [comment]
@junegunn I've attempted to use this snippet, but I keep getting an error when attempting to delete a buffer, the error is:

```
Error detected while processing function 21[30]..<SNR>64_callback:
line   21:
Vim(redir):E930: Cannot use :redir inside execute() 
```

[example video](https://cdn.discordapp.com/attachments/365662117191352320/676605748188413974/screencast_2020-02-10_17-49-01.mp4)

**Comment by junegunn** [comment]
@amadeus For some reason, the original code I posted above only worked on Neovim and not on Vim. I updated the comment with the revised version that works on both.

**Comment by lioaslan** [comment]
@junegunn How can I fix code on [this](https://github.com/junegunn/fzf.vim/pull/733#issuecomment-559720813) to delete selecting buffer when I'm on `:Buffers` window?

**Comment by kyoh86** [comment]
@lioaslan 

```
    function! s:delete_buffers()
      let l:preview_window = get(g:, 'fzf_preview_window', &columns >= 120 ? 'right': '')
      let l:options = [
      \   '-m',
      \   '--tiebreak=index',
      \   '-d', '\t',
      \   '--prompt', 'Delete> '
      \ ]
      if len(l:preview_window)
        let l:options = extend(l:options, get(fzf#vim#with_preview(
              \   {"placeholder": "{2}"},
              \   l:preview_window
              \ ), 'options', []))
      endif


      return fzf#run(fzf#wrap({
      \ 'source':  map(
      \   filter(
      \     range(1, bufnr('$')),
      \     {_, nr -> buflisted(nr) && !getbufvar(nr, "&modified")}
      \   ),
      \   {_, nr -> s:format_buffer(nr)}
      \ ),
      \ 'sink*': {
      \   lines -> execute('bdelete ' . join(map(lines, {
      \     _, line -> substitute(split(line)[0], '^\[\|\]$', '', 'g')
      \   })), 'silent!')
      \ },
      \ 'options': l:options,
      \}))
    endfunction
```

How's this?

**Comment by lioaslan** [comment]
I got `Unknow function: s:format_buffer(nr)` error.
Is that function implemented by myself?

**Comment by kyoh86** [comment]
@lioaslan 
```vim
    function! s:format_buffer(b)
      let l:name = bufname(a:b)
      let l:name = empty(l:name) ? '[No Name]' : fnamemodify(l:name, ":p:~:.")
      let l:flag = a:b == bufnr('')  ? '%' :
              \ (a:b == bufnr('#') ? '#' : ' ')
      let l:modified = getbufvar(a:b, '&modified') ? ' [+]' : ''
      let l:readonly = getbufvar(a:b, '&modifiable') ? '' : ' [RO]'
      let l:extra = join(filter([l:modified, l:readonly], '!empty(v:val)'), '')
      return substitute(printf("[%s] %s\t%s\t%s", a:b, l:flag, l:name, l:extra), '^\s*\|\s*$', '', 'g')
    endfunction
```

**Comment by TheMeaningfulEngineer** [comment]
Hey,
does anyone know how if this can be done by extending `g:fzf_action`?

The expected behavior is to close the selected one/multiple muffers with `ctrl+d`.

I've attempted this:

```
let g:fzf_action = {
  \ 'ctrl-d': 'bd!',
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

It closes the buffer which was active once `:Buffers` was started instead of the selected buffers.


I've tried also reusing:

```
function! s:delete_buffers(lines)
  execute 'bwipeout' join(map(a:lines, {_, line -> split(line)[0]}))
endfunction

let g:fzf_action = {
  \ 'ctrl-d': function('s:delete_buffers'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

with the same result.

**Comment by linrongbin16** [comment]
Hi, I have come up with my solution:

```

function! s:buffers_delete(lines)
    echo 'lines:'.string(a:lines)            " Note: here print log for a:lines
    normal! m'
    let action = a:lines[1]
    if action !=? 'ctrl-x'
        return
    endif
    let buf=split(a:lines[2])[0]
    let bufname=split(buf, ':')[0]
    execute 'bdelete '.bufname
endfunction

function! s:myfzfbuffers(query, fullscreen)
    let close_buffer_header=':: <ctrl-x> to Close Buffer'
    " let spec = { 'source': s:buffers_list(),
    "             \ 'sink*': { lines -> s:buffers_delete(lines) },
    "             \ 'options': [
    "             \   '--print-query',
    "             \   '--header', close_buffer_header,
    "             \   '--prompt', 'Buffer> '
    "             \ ]}
    " call fzf#run(fzf#wrap('buffers', fzf#vim#with_preview(spec), a:fullscreen))
    let spec = { 'sink*': { lines -> s:buffers_delete(lines) },
                \ 'options': [
                \   '--print-query',
                \   '--header', close_buffer_header,
                \   '--prompt', 'Buffer> '
                \ ],
                \ 'placeholder': '{1}'
                \ }
    call fzf#vim#buffers(a:query, fzf#vim#with_preview(spec), a:fullscreen)
endfunction


command! -bar -bang -nargs=? -complete=dir MyFzfBuffers call s:myfzfbuffers(<q-args>, <bang>0)
```

It uses the default `fzf#vim#buffers` API (it has great support for not selecting current buffer), and I want to use `ctrl-x` to delete selected buffers.

**Comment by noboruma** [comment]
For the lazy, here is the solution from @linrongbin16 (kudos to you!):
```
let s:default_action = {
            \ 'ctrl-t': 'tab split',
            \ 'ctrl-x': 'split',
            \ 'ctrl-v': 'vsplit' }
function! s:action_for(key, ...)
    let default = a:0 ? a:1 : ''
    let Cmd = get(get(g:, 'fzf_action', s:default_action), a:key, default)
    return type(Cmd) == s:TYPE.string ? Cmd : default
endfunction

function! s:find_open_window(b)
    let [tcur, tcnt] = [tabpagenr() - 1, tabpagenr('$')]
    for toff in range(0, tabpagenr('$') - 1)
        let t = (tcur + toff) % tcnt + 1
        let buffers = tabpagebuflist(t)
        for w in range(1, len(buffers))
            let b = buffers[w - 1]
            if b == a:b
                return [t, w]
            endif
        endfor
    endfor
    return [0, 0]
endfunction

function! s:jump(t, w)
    execute a:t.'tabnext'
    execute a:w.'wincmd w'
endfunction

function! s:buffers_sink(lines, query, fullscreen)
    if len(a:lines) < 3
        return
    endif
    let b = matchstr(a:lines[2], '\[\zs[0-9]*\ze\]')
    let bufname=split(a:lines[2])[-1]
    let action = a:lines[1]
    if empty(action)
        let [t, w] = s:find_open_window(b)
        if t
            call s:jump(t, w)
            return
        endif
        execute 'buffer' b
        return
    endif
    if action==?'ctrl-d'
        execute 'bdelete' b
        call s:custom_buffer(a:query, a:fullscreen)
    else
        let cmd = s:action_for(action)
        if !empty(cmd)
            execute 'silent' cmd
        endif
        execute 'buffer' b
    endif
endfunction

function! s:custom_buffer(query, fullscreen)
    let spec = { 'sink*': {lines -> s:buffers_sink(lines, a:query, a:fullscreen)},
                \ 'options': [
                \   '--print-query',
                \   '--prompt', 'Buffer> '
                \ ],
                \ 'placeholder': '{1}'
                \ }
    let spec._action = get(g:, 'fzf_action', s:default_action)
    call add(spec.options, '--expect=ctrl-d,'.join(keys(spec._action), ','))
    call fzf#vim#buffers(a:query, fzf#vim#with_preview(spec), a:fullscreen)
endfunction
command! -bar -bang -nargs=? -complete=dir FzfxBuffers call s:custom_buffer(<q-args>, <bang>0)
```

**Comment by junegunn** [comment]
31e338e3143eddd6dbc424870899af28d987d30f

**Pull request closed without merging**
