### PR TITLE
expand '~' in preview

### PR DESCRIPTION
**Pull request by zhou13**
In preview mode, with this pull request it can correctly handle `~` in the path. Using `:call fzf#vim#history(fzf#vim#with_preview({'options': '--no-sort'}))` to test.

### CODE REVIEW

**Comment by zhou13** [comment]
Will the pull requests be merged?

**Comment by junegunn** [comment]
Please make sure that the code only replaces `~/`, it won't work with `~username`.

**Comment by zhou13** [comment]
To do that correctly, I think the correct way is to use 
````
expandPath() {
  local path
  local -a pathElements resultPathElements
  IFS=':' read -r -a pathElements <<<"$1"
  : "${pathElements[@]}"
  for path in "${pathElements[@]}"; do
    : "$path"
    case $path in
      "~+"/*)
        path=$PWD/${path#"~+/"}
        ;;
      "~-"/*)
        path=$OLDPWD/${path#"~-/"}
        ;;
      "~"/*)
        path=$HOME/${path#"~/"}
        ;;
      "~"*)
        username=${path%%/*}
        username=${username#"~"}
        IFS=: read _ _ _ _ _ homedir _ < <(getent passwd "$username")
        if [[ $path = */* ]]; then
          path=${homedir}/${path#*/}
        else
          path=$homedir
        fi
        ;;
    esac
    resultPathElements+=( "$path" )
  done
  local result
  printf -v result '%s:' "${resultPathElements[@]}"
  printf '%s\n' "${result%:}"
}
````
from https://stackoverflow.com/questions/3963716/how-to-manually-expand-a-special-variable-ex-tilde-in-bash.  Any suggestions?

**Comment by junegunn** [comment]
No, full-fledged support for tilde expansion is too much. I'm just asking you to update the code to replace `~/` to `$HOME/`.

**Comment by junegunn** [comment]
Fixed in #892.

**Pull request closed without merging**
