### PR TITLE
Make `s:p()` public for user fzf extensions?

### PR DESCRIPTION
**Pull request by jesseleite**
Make `s:p()` public for user fzf extensions?  (See #1013 for use case example.)

### CODE REVIEW

**Comment by junegunn** [comment]
The function was added quite recently without too much thought and I'm not exactly happy with the way it works because those hard-coded numbers are meaningless to me now as I have configured my fzf to open in a tmux popup window (`let g:fzf_layout = { 'tmux': '-p90%,60%' }`). It needs further consideration. Actually the function is more like a set of some arbitrary rules that are not universally agreed upon so users don't really have to use it.

**Comment by jesseleite** [comment]
>It needs further consideration.

Fair enough.

**Comment by jesseleite** [comment]
>It needs further consideration.

Fair enough.  Whatever you land on though, it would be nice if it was eventually public, so that user extensions can easily piggy back without having to write/copy `g:fzf_preview_window` logic 🙂

**Comment by junegunn** [comment]
Hi, now we no longer have `s:p()` and `fzf#vim#with_preview` will process `g:fzf_preview_window`.

```vim
let g:fzf_preview_window = ['up', 'ctrl-/']
echo fzf#vim#with_preview()
  " {'options': ['--preview-window', 'up', '--preview', '''/Users/jg/.vim/plugged/fzf.vim/bin/preview.sh'' {}', '--bind', 'ctrl-/:toggle-preview']}

let g:fzf_preview_window = []
echo fzf#vim#with_preview()
  " {'options': ['--preview-window', 'hidden', '--preview', '''/Users/jg/.vim/plugged/fzf.vim/bin/preview.sh'' {}']}
```

**Comment by jesseleite** [comment]
Right on, thanks for the info!

**Pull request closed without merging**
