### PR TITLE
Add `Resume` command

### PR DESCRIPTION
**Pull request by artemave**
### What

A command that opens last used fzf command buffer (with the query).

Example mapping:

```vimscript
nnoremap <leader>u :Resume<cr>
```

### Why

Because I often run the same query. And I am missing `UniteResume`

cc #182

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, but I don't want to merge this. You could just write a general-purpose command wrapper and use it.

```vim
function! s:remember(command)
  execute a:command
  " Or save it to a file for persistence
  let g:prev_command = a:command
endfunction

command! -nargs=* Remember call s:remember(<q-args>)
command! Redo execute g:prev_command
```
Then you can `:Remember Ag foo` and `:Redo`. You can use it with any commands with any arguments.

**Comment by artemave** [comment]
This is interesting - it didn't occur to me that it could be a command wrapper. One thing is not clear though: how would I go about restoring fzf `--query` in this case?

**Comment by artemave** [comment]
@junegunn how would I go about restoring fzf query in case of a wrapper?

Using `<c-p>` does not work because it picks up a query from the last command _with a query_, and that may not have necessarily been the last command.

**Comment by junegunn** [comment]
So if I understood correctly, you want to maintain separate query history for each command with different arguments. i.e. `Ag foo`, `Ag bar`, ...

Sorry but it's not something I want to add to this project. I personally never needed such a feature (actually I don't even use `g:fzf_history_dir`), and I don't like that it'll create a bunch of history files.

Note that you can manually override `--history` option:

```vim
let g:fzf_history_dir = '/tmp/fzf-history'

echo fzf#wrap('type1').options
echo fzf#wrap('type1', { 'options': ['--history', '/tmp/fzf-history/type2'] }).options
```

So you can write your own version of each command,

```vim
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': ['--history', g:fzf_history_dir.'/rg-'.<q-args>]}, <bang>0)
```

and combine with `Remember` command shown above.

**Comment by artemave** [comment]
> So if I understood correctly, you want to maintain separate query history for each command with different arguments.

Well, fzf history (or perhaps fzf.vim?) creates a different query history file for each command (including custom commands) already:

```
% ls ~/.fzf-history/
buffers  files  gfiles-diff  history-files  lines  marks  rg  tags
```

I simply take advantage of that feature to look up the last query for a command (I do keep track of a last command, but there is no way to know the actual query since it happens inside fzf itself).

**Comment by artemave** [comment]
Update: I am using `Resume` _all_ the time. I also keep my fork up-to-date. In case you ever change your mind!

**Comment by artemave** [comment]
Update: improved the implementation such that it now remembers the last query even if the user didn't press enter. That's useful when browsing through files with preview without actually opening any.

**Pull request closed without merging**
